#!/usr/bin/env python
import argparse
import subprocess

def run(pfile, rate, rfile, output):
    ports = ''
    for line in open(pfile, 'r'):
        line = line.rstrip('\r\n')
        if line.startswith('#') or len(line) < 1:
            continue
        port = line.split(' ')[0]
        if len(port) > 0:
            ports += '%s,' % port
    ports = ports.rstrip(', ')
    masscan(ports, rate, rfile, output)

def masscan(ports, rate, rfile, output):
    print 'masscan', '--exclude', '255.255.255.255', '-p', ports, '--rate', rate, '-iL', rfile, '-oL', output, '--connection-timeout', '100'
    p = subprocess.Popen(
        ['masscan', '--exclude', '255.255.255.255', '-p', ports, '--rate', rate, '-iL', rfile, '-oL', output, '--connection-timeout', '100'])
    p.wait()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("pfile", help="port file")
    parser.add_argument("rate", help="packets per sec")
    parser.add_argument("rfile", help="range file")
    parser.add_argument("output", help="output dir")
    args = parser.parse_args()
    run(args.pfile, args.rate, args.rfile, args.output)

