#!/usr/bin/env python
import os
import argparse
import subprocess

def run(pfile, rate, rfile, output):
    for line in open(pfile, 'r'):
        port = line.split(' ')[0]
        masscan(port, rate, rfile, os.path.join(output, port))

def masscan(port, rate, rfile, output):
    p = subprocess.Popen(
        ['masscan', '-p', port, '--rate', rate, '-iL', rfile, '-oL', output, '--connection-timeout', '100',
         '--banners', '--exclude', '255.255.255.255', '--http-user-agent', 'Mozilla/5.0 (Windows NT 6.3; WOW64)',
         '--capture', 'html'])
    p.wait()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("pfile", help="port file")
    parser.add_argument("rate", help="packets per sec")
    parser.add_argument("rfile", help="range file")
    parser.add_argument("output", help="output dir")
    args = parser.parse_args()
    run(args.pfile, args.rate, args.rfile, args.output)

