#!/bin/bash

PFILE="ports"
RATE="8000"
RANGEDIR="/home/ssem/ranges/ranges$1"
TMPDIR="/tmp"
OUTPUTDIR="/home/ssem/fingerprint"

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

for f in `ls ${RANGEDIR}`;
do
    if [ ${f} != "create_ranges" ]
    then
        mkdir ${TMPDIR}/${f}
        mkdir ${OUTPUTDIR}/${f}
        ./mass ${PFILE} ${RATE} ${RANGEDIR}/${f} ${TMPDIR}/${f}
        ./fingerprint ${TMPDIR}/${f} ${OUTPUTDIR}/${f}
        rm -r ${TMPDIR}/${f}
    fi
done
