#!/bin/bash


if [[ -z  "$1" ]]
then
    printf "\n\tUsage: < input file >\n\n"
else
    # credit cards
    #cat $@ | egrep -o '\b4[0-9]{3}[ -]?[0-9]{4}[ -]?[0-9]{4}[ -]?[0-9]{1}[0-9]{3}?\b' >> visa.txt
    #cat $@ | egrep -o '\b5[1-5][0-9]{2}[ -]?[0-9]{4}[ -]?[0-9]{4}[ -]?[0-9]{4}\b' >> mastercard.txt
    #cat $@ | egrep -o '\b3[47][0-9]{2}[ -]?[0-9]{6}[ -]?[0-9]{5}\b' >> americal-express.txt
    #cat $@ | egrep -o '\b3(0[0-5]|[68][0-9])[0-9]{1}[0-9]{6}[0-9]{4}\b' >> diners_club.txt
    #cat $@ | egrep -o '\b6(011|5[0-9]{2})[ -]?[0-9]{4}[ -]?[0-9]{4}[ -]?[0-9]{4}\b' >> discover.txt
    #cat $@ | egrep -o '\b(2131|1800|35[0-9]{2})[ -]?[0-9]{4}[ -]?[0-9]{4}[ -]?[0-9]{3,4}\b' >> jcb.txt

    # other
    #cat $@ | egrep -o '\b[0-9]{3}[ -]{1}[0-9]{2}[ -]{1}[0-9]{4}\b' > ssn.txt
    #cat $@ | egrep -o '\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b' >> email.txt

    #hashes
    #cat $@ | egrep -o '^\w{32}($|\s)' >> md5_raw-md4_nt_lotus5.txt
    #cat $@ | egrep -o '^\w{40}($|\s)' >> raw-sha1_ripemd-160_mysql-sha1.txt
    #cat $@ | egrep -o '^\w{16}($|\s)' >> mysql_pix-md5_lm.txt
    #cat $@ | egrep -o '\w*:\*\w{40}($|\s)' >> mysql-sha1.txt
    #cat $@ | egrep -o '\$[P|H]\$\S{31}($|\s)' >> phpass.txt
    #cat $@ | egrep -o '\$1\$\w{8}\$\S{22}($|\s)' >> raw-md5.txt
    #cat $@ | egrep -o '^\w{32}:\S*($|\s)' >> mscash_salt.txt
    #cat $@ | egrep -o 'M\$\S*\#\w{32}:\S*($|\s)' >> mscash_salt2.txt
    #cat $@ | egrep -o 'M\$\S*\#\w{32}($|\s)' >> mscash.txt
    #cat $@ | egrep -o '^\w{64}($|\s)' >> raw-sha256_ghost.txt
    #cat $@ | egrep -o '^\S{13}($|\s)' >> descrypt.txt
    #cat $@ | egrep -o '^\w*:\S{13}($|\s)' >> descrypt_user.txt
    #cat $@ | egrep -o '\$apr1\$\w{8}\$\S{22}($|\s)' >> md5crypt.txt
    #cat $@ | egrep -o '^\w{128}($|\s)' >> raw-sha512_whirlpool.txt
    #cat $@ | egrep -o '\$6\$\w*\$\S{86}($|\s)' >> sha512crypt.txt
    #cat $@ | egrep -o '\$DCC2\$10240\#\w*\#\w{32}($|\s)' >> mscash2.txt
    #cat $@ | egrep -o '\$LM\$\w{16}($|\s)' >> lm.txt
    #cat $@ | egrep -o '^\w{16}:\w*($|\s)' >> oracle_salt.txt
    #cat $@ | egrep -o '^O\$\w*\#\w{16}($|\s)' >> oracle_salt2.txt
    #cat $@ | egrep -o '^\w+:O\$\w*\#\w{16}($|\s)' >> oracle_user.txt
    #cat $@ | egrep -o '\$2a\$\w*\$\S{53}($|\s)' >> bcrypt.txt
    #cat $@ | egrep -o '\$md5\$rounds=\w*\$\S{39}($|\s)' >> sunmd5.txt
    #cat $@ | egrep -o 'u4-netntlm::\w*:\S{114}($|\s)' >> netntlm.txt
    #cat $@ | egrep -o '\w*::\w*:\S{156}($|\s)' >> netntlmv2.txt
    #cat $@ | egrep -o '\{smd5\}\S{31}($|\s)' >> aix-smd5.txt
    #cat $@ | egrep -o '\{ssha256\}\S{63}($|\s)' >> aix-ssha256.txt
    #cat $@ | egrep -o '\{ssha512\}\S{106}($|\s)' >> aix-sha512.txt
    #cat $@ | egrep -o '\{ssha1\}\S{47}($|\s)' >> aix-ssha1.txt
    #cat $@ | egrep -o '^\w{47}($|\s)' >> forigate.txt
    #cat $@ | egrep -o '\$\w*\$\w*\$\w{128}($|\s)' >> pbkdf2-hmac-sha512.txt
    #cat $@ | egrep -o 'grub.pbkdf2.sha512.\w*.\S{257}($|\s)' >> pbkdf2-hmac-sha512.txt
    #cat $@ | egrep -o '^\w{130}($|\s)' >> lotus85.txt
    #cat $@ | egrep -o '\$5\Srounds=\w*\$\S{60}($|\s)' >> sha256crypt.txt
    #cat $@ | egrep -o '^\w*\$\w{16}($|\s)' >> sapb.txt
    #cat $@ | egrep -o '^\w*\$\w{40}($|\s)' >> sapg.txt
    #cat $@ | egrep -o '\$S\$\S{52}($|\s)' >> drupal7.txt
    #cat $@ | egrep -o '^\w{86}($|\s)' >> sybasease.txt
    #cat $@ | egrep -o '^\w{49}($|\s)' >> citrix_ns10.txt
    #cat $@ | egrep -o '\$racf\$\*\w*\*\w{16}($|\s)' >> racf.txt
    #cat $@ | egrep -o '\$8\$\S{58}($|\s)' >> pbkdf2-hmac-sha256.txt
    #cat $@ | egrep -o '\$office\$\*20(07|10|13)\*\w*\*\w*\*\w*\*(\S{106}|\S{130})($|\s)' >> office.txt
    #cat $@ | egrep -o '\$oldoffice\$\w*\*(\S{98}|\S{106})($|\s)' >> oldoffice.txt
    #cat $@ | egrep -o '^\w{96}($|\s)' >> raw-sha384.txt
fi
