#!/bin/bash

DIR="/mnt/movies/other/pastebin/"
IN=`cat $@`

# credit cards
#echo ${IN} | egrep -o '\b4[0-9]{3}[ -]?[0-9]{4}[ -]?[0-9]{4}[ -]?[0-9]{1}[0-9]{3}?\b' >> ${DIR}visa.txt
#echo ${IN} | egrep -o '\b5[1-5][0-9]{2}[ -]?[0-9]{4}[ -]?[0-9]{4}[ -]?[0-9]{4}\b' >> ${DIR}mastercard.txt
#echo ${IN} | egrep -o '\b3[47][0-9]{2}[ -]?[0-9]{6}[ -]?[0-9]{5}\b' >> ${DIR}americal-express.txt
#echo ${IN} | egrep -o '\b3(0[0-5]|[68][0-9])[0-9]{1}[0-9]{6}[0-9]{4}\b' >> ${DIR}diners_club.txt
#echo ${IN} | egrep -o '\b6(011|5[0-9]{2})[ -]?[0-9]{4}[ -]?[0-9]{4}[ -]?[0-9]{4}\b' >> ${DIR}discover.txt
#echo ${IN} | egrep -o '\b(2131|1800|35[0-9]{2})[ -]?[0-9]{4}[ -]?[0-9]{4}[ -]?[0-9]{3,4}\b' >> ${DIR}jcb.txt

# other
#echo ${IN} | egrep -o '\b[0-9]{3}[ -]{1}[0-9]{2}[ -]{1}[0-9]{4}\b' > ${DIR}ssn.txt
echo ${IN} | egrep -o '\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b' >> ${DIR}email.txt

#hashes
echo ${IN} | egrep -o '^\w{32}($|\s)' >> ${DIR}md5_raw-md4_nt_lotus5.txt
echo ${IN} | egrep -o '^\w{40}($|\s)' >> ${DIR}raw-sha1_ripemd-160_mysql-sha1.txt
echo ${IN} | egrep -o '^\w{16}($|\s)' >> ${DIR}mysql_pix-md5_lm.txt
echo ${IN} | egrep -o '\w*:\*\w{40}($|\s)' >> ${DIR}mysql-sha1.txt
echo ${IN} | egrep -o '\$[P|H]\$\S{31}($|\s)' >> ${DIR}phpass.txt
echo ${IN} | egrep -o '\$1\$\w{8}\$\S{22}($|\s)' >> ${DIR}raw-md5.txt
echo ${IN} | egrep -o '^\w{32}:\S*($|\s)' >> ${DIR}mscash_salt.txt
echo ${IN} | egrep -o 'M\$\S*\#\w{32}:\S*($|\s)' >> ${DIR}mscash_salt2.txt
echo ${IN} | egrep -o 'M\$\S*\#\w{32}($|\s)' >> ${DIR}mscash.txt
echo ${IN} | egrep -o '^\w{64}($|\s)' >> ${DIR}raw-sha256_ghost.txt
echo ${IN} | egrep -o '^\S{13}($|\s)' >> ${DIR}descrypt.txt
echo ${IN} | egrep -o '^\w*:\S{13}($|\s)' >> ${DIR}descrypt_user.txt
echo ${IN} | egrep -o '\$apr1\$\w{8}\$\S{22}($|\s)' >> ${DIR}md5crypt.txt
echo ${IN} | egrep -o '^\w{128}($|\s)' >> ${DIR}raw-sha512_whirlpool.txt
echo ${IN} | egrep -o '\$6\$\w*\$\S{86}($|\s)' >> ${DIR}sha512crypt.txt
echo ${IN} | egrep -o '\$DCC2\$10240\#\w*\#\w{32}($|\s)' >> ${DIR}mscash2.txt
echo ${IN} | egrep -o '\$LM\$\w{16}($|\s)' >> ${DIR}lm.txt
echo ${IN} | egrep -o '^\w{16}:\w*($|\s)' >> ${DIR}oracle_salt.txt
echo ${IN} | egrep -o '^O\$\w*\#\w{16}($|\s)' >> ${DIR}oracle_salt2.txt
echo ${IN} | egrep -o '^\w+:O\$\w*\#\w{16}($|\s)' >> ${DIR}oracle_user.txt
echo ${IN} | egrep -o '\$2a\$\w*\$\S{53}($|\s)' >> ${DIR}bcrypt.txt
echo ${IN} | egrep -o '\$md5\$rounds=\w*\$\S{39}($|\s)' >> ${DIR}sunmd5.txt
echo ${IN} | egrep -o 'u4-netntlm::\w*:\S{114}($|\s)' >> ${DIR}netntlm.txt
echo ${IN} | egrep -o '\w*::\w*:\S{156}($|\s)' >> ${DIR}netntlmv2.txt
echo ${IN} | egrep -o '\{smd5\}\S{31}($|\s)' >> ${DIR}aix-smd5.txt
echo ${IN} | egrep -o '\{ssha256\}\S{63}($|\s)' >> ${DIR}aix-ssha256.txt
echo ${IN} | egrep -o '\{ssha512\}\S{106}($|\s)' >> ${DIR}aix-sha512.txt
echo ${IN} | egrep -o '\{ssha1\}\S{47}($|\s)' >> ${DIR}aix-ssha1.txt
echo ${IN} | egrep -o '^\w{47}($|\s)' >> ${DIR}forigate.txt
echo ${IN} | egrep -o '\$\w*\$\w*\$\w{128}($|\s)' >> ${DIR}pbkdf2-hmac-sha512.txt
echo ${IN} | egrep -o 'grub.pbkdf2.sha512.\w*.\S{257}($|\s)' >> ${DIR}pbkdf2-hmac-sha512.txt
echo ${IN} | egrep -o '^\w{130}($|\s)' >> ${DIR}lotus85.txt
echo ${IN} | egrep -o '\$5\Srounds=\w*\$\S{60}($|\s)' >> ${DIR}sha256crypt.txt
echo ${IN} | egrep -o '^\w*\$\w{16}($|\s)' >> ${DIR}sapb.txt
echo ${IN} | egrep -o '^\w*\$\w{40}($|\s)' >> ${DIR}sapg.txt
echo ${IN} | egrep -o '\$S\$\S{52}($|\s)' >> ${DIR}drupal7.txt
echo ${IN} | egrep -o '^\w{86}($|\s)' >> ${DIR}sybasease.txt
echo ${IN} | egrep -o '^\w{49}($|\s)' >> ${DIR}citrix_ns10.txt
echo ${IN} | egrep -o '\$racf\$\*\w*\*\w{16}($|\s)' >> ${DIR}racf.txt
echo ${IN} | egrep -o '\$8\$\S{58}($|\s)' >> ${DIR}pbkdf2-hmac-sha256.txt
echo ${IN} | egrep -o '\$office\$\*20(07|10|13)\*\w*\*\w*\*\w*\*(\S{106}|\S{130})($|\s)' >> ${DIR}office.txt
echo ${IN} | egrep -o '\$oldoffice\$\w*\*(\S{98}|\S{106})($|\s)' >> ${DIR}oldoffice.txt
echo ${IN} | egrep -o '^\w{96}($|\s)' >> ${DIR}raw-sha384.txt

for f in ${DIR}*; do
    cat $f | sort | uniq > ${DIR}tmp
    mv ${DIR}tmp $f
done
