#!/usr/bin/env python
import argparse
import requests

class Pastebin():
    def __init__(self, path):
        self.path = path
        self.quote = "Soon, I'm going to meet somebody around my own age, "
        self.quote += "and she's going to be smart and beautiful, "
        self.quote += "and I'm going to date her daughter."

    def run(self):
        for page in self.scrape_archive():
            self.scrape_page(page)

    def scrape_page(self, page):
        http = requests.get(
            url='http://pastebin.com/raw.php?i=%s' % page,
            headers={'user-agent':self.quote})
        if self.path:
            path = '%s/%s' % (self.path, page)
            p = open(path, 'w+')
            p.write(http.content)
            p.close()
        else:
            print http.content

    def scrape_archive(self):
        http = requests.get(
            url='http://pastebin.com/archive',
            headers={'user-agent':self.quote})
        for line in http.content.split('\n'):
            if 'border="0" /><a href="/' in line:
               yield line.split('<a href="/')[-1].split('">')[0]

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--path', help='path to store data')
    args = parser.parse_args()
    pastebin = Pastebin(args.path)
    pastebin.run()
